server:
  port: 8012

spring:
  application:
    name: eureka-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8012/eureka
  instance:
    prefer-ip-address: true
