spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/huaweimarketdb
    username: huawei
    password: huawei
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  main:
    allow-circular-references: true
  messages:
    basename: exception
  liquibase:
    enabled: true
  change-log: classpath:/db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: huawei-market
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
        use-default-response-messages: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8012/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

huawei:
  market:
    customized:
      order:
        policy: cookies policy v2
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, env