eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8012/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: product-service
  devtools:
    restart:
      enabled: true
  main:
    allow-circular-references: true
  messages:
    basename: exception
  datasource:
    url: jdbc:postgresql://localhost:5432/huaweimarketdb
    username: huawei
    password: huawei
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: huawei-market

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
        use-default-response-messages: false

resilience4j:
  circuitbreaker:
    instances:
      slowService:
        register-health-indicator: true
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 2
        automatic-transition-from-open-to-half-open-enabled: true

  timelimiter:
    instances:
      slowService:
        timeout-duration: 100ms
